## Github Actions simple CI workflow
name: CI

on:
  # Triggers the workflow on push or pull request events on the master branch
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  # Allows to run the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "16.0"
      FLUTTER_VERSION: "2.5.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16.0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.5.3
      # Commands to run:
      # Run pub get to assure dependencies are built in
      - run: flutter pub get
      # Run analyzer to check for bad Dart/Flutter practices
      - run: flutter analyze
      # Run all app tests
      - run: flutter test